### ISSUE TITLE
Drawing opcodes section could be clarified

### ISSUE THREAD

**Issue by Hixie** [google/iconvg#18]
The drawing opcodes section is a bit confusing. First, the deference to SVG makes everything have an additional level of (very ambiguous) indirection, which is really confusing. SVG is defining all this in the context of a text attribute, not an abstract data model, so a great deal of squinting and hand-waving is required to strictly map the IconVG definition to the SVG spec text.

There's also some more specific issues in this text. For example, it's not 100% clear exactly how to interpret the parameters, for example:

> The opcode is followed by (2 * RC) coordinates, RC sets of (x, y).

...presumably is intended to mean that you read two coordinate numbers and apply the "lineto" command for those two numbers, RC times overall? There's a lot of vagueness here that is only really disambiguated by guessing at the most likely intention based on knowing how SVG path data works, which is not ideal for a spec. :-)

**Comment by Hixie** [comment]
One thing that really should be more clearly specified is exactly how the opcodes corresponding to s/S and t/T handle their implied reflected control point. For example, if we specify that invalid opcodes are ignored rather than fatal errors, should those reset the "old control point" registers?

**Comment by Hixie** [comment]
Another example of how the current way this is specified leads to confusion is the opcode corresponding to `A`. The IconVG spec says "The xAxisRotation number is an angle (a zero-to-one number being a fraction of 360 degrees)", but the SVG spec says "x-axis-rotation, which indicates how the ellipse as a whole is rotated, in degrees". And neither specifies if it's clockwise or counter-clockwise...

**Comment by nigeltao** [comment]
The whole thread has valid questions, but just focusing on the most recent two (in reverse order):


> Another example of how the current way this is specified leads to confusion is the opcode corresponding to A.

Dropping the `A/a` opcodes in a File Format Version bump (as proposed in https://github.com/google/iconvg/issues/4) would avoid the whole issue.


> One thing that really should be more clearly specified is exactly how the opcodes corresponding to s/S and t/T handle their implied reflected control point.

If we're dropping `A/a`, so that we're no longer taking the entirety of the SVG path model, I'm tempted to also drop `S/s` and `T/t` too (and push the "calculate the implied reflected control point" responsibility to the "convert from SVG" authoring tools). File sizes might be very slightly larger, but it would simplify the spec (and the implementations) regarding questions like this.

**Comment by Hixie** [comment]
I would certainly support dropping opcodes and generally simplifying the format, but I would recommend making such decisions based on what the format's goals are. If file size is a higher concern than implementation and spec complexity, then these opcodes do make sense. If rendering speed is more important then there's plenty of other places to optimize, for example the 1- and 2- byte encodings for numbers do not add any value beyond file size optimization but cost implementation complexity and size and runtime performance. I would urge any changes to be made at a holistic level; making decisions in one part of the format with different priorities than in another part of the format will lead to a confused format.

**Comment by nigeltao** [comment]
Point taken about a holistic approach.

Specifically on file size, here's some stats on the 2016 era Material Design icon suite [re-encoded as IconVG](https://github.com/golang/exp/tree/master/shiny/materialdesign/icons).

```
961 files, 122012 total bytes; averaging 126.96 bytes per file

Coordinate Byte-Length (Percent; Count; Weighted)
1     60.73 %   40324   *1= 40324
2     39.27 %   26079   *2= 52158
SUM  100.00 %   66403       92482
```

So, coordinates take up 92482 / 122012 = 76% of the bytes. These were encoded without the 'High Resolution Coordinates' option (i.e. coordinates *are* quantized to avoid 4-byte encodings). The [HRC documentation comment](https://github.com/golang/exp/blob/29119ec56d8af785c271d6adb38d1dd742d94b62/shiny/iconvg/encode.go#L50-L51) says:

> On the Material Design icon set, the 950 or so icons take up around 40% more bytes (172K vs 123K) at high resolution.

Note that enabling HRC isn't "encode only in 4-bytes per coordinate", it's "do so only if you can't represent in 1 or 2 bytes".

If we simplified the format to *only* have 4-bytes per coordinate, this would add (40324*(4-1)) + (26079*(4-2)) = 173130 bytes, basically ~~doubling~~ (_Edit: increasing by 173130 / 122012 = +142%_) the overall file size on this icon suite.

I think that's a big cost. Conversely, I'd expect the bulk of the CPU/GPU time to be spent rasterizing vectors instead of decoding 1-byte numbers, even if rasterization can be parallelized. That's just a guess though, I don't have data at hand.

**Comment by Hixie** [comment]
If the coordinates were 32bit big-endian 4-byte aligned in the data file, we could move them to the CPU with a single instruction and use SIMD instructions when applying math to them, or we could move them to the GPU as a single block and have a shader manipulate them without any work on the CPU to decode them at all. That might save us, say, 10μs. (That number is entirely made up. The value matters in practice, but not for the purposes of this conversation.)

Similarly, if we didn't support the opcodes analogous to `S`/`s` and `T`/`t`, we could save maybe 5KB of the implementation footprint, maybe 30 minutes of implementation time per implementation (encoders and decoders), maybe 1 bug per implementation. Call all that _Q_. If we did support the opcodes, we could save maybe 1KB over your dataset (again, the precise numbers don't matter). Call that _R_.

The question isn't whether 173KB is a big cost or not, any more than the question is whether 10μs is too big a cost or not, or Q is too big a cost, or R is too big a cost.

The question is what are we optimising for, and, _given that_, whether 173KB is worth more than 10μs, or whether 10μs is worth more than 173KB, and whether Q is worth more than R, or R is worth more than Q.

FWIW, in Flutter land we are dealing with 4ms windows to render content (4ms build + 4ms raster, to make an 8ms frame budget for 120Hz). Right now an IconVG image on a Pixel 3XL takes about 200μs on the build side (about 5% of the build budget). That's not slow, but it's also not fast. If we could save 10μs per image, that's 5% of the current cost of building an image. That's significant. On the other hand, 173KB for the entire icon set is barely a blip on the radar -- it's not like applications would build the entire icon set. Right now the material icons font we use is 1.2MB (we do tree-shake that down to the icons that the app uses).

My point here is not to argue that we should optimize IconVG for render speed -- quite the contrary. A format optimized for that would be a completely different format with a different feature set, and would bear little resemblance to IconVG. My point is just what I said above, that the format's priorities should be clearly stated, then all the decisions made with that in mind. I don't know if the shorthand opcodes actually save any file size. If they don't, then maybe they have no redeeming value and the discussion is moot. On the other hand, if they do, then what problem does removing them solve? Weight the size of that problem by the priority of that problem, weight the size of the benefit they give by the priority of that benefit, and compare the weighted values to come to a decision.

I'm sorry, I'm just rambling here.

**Comment by nigeltao** [comment]
> Right now an IconVG image on a Pixel 3XL takes about 200μs on the build side

I'm not familiar with Flutter terminology. Does "build" basically mean "parse, but not including any time spent in e.g. Skia or waiting for the GPU"? In a similar vein, do you know how much of that 200μs is "fixed cost" and how much of that changes if you e.g. quadruple the number of pixels you render at (double the width and double the height)?

**Comment by nigeltao** [comment]
> I'm tempted to also drop `S/s` and `T/t`

Some more numbers from the same 961-file icon suite:

```
Drawing OpCodes (Percent; Count)
C      2.34 %     571
H      6.25 %    1529
L      5.37 %    1314
S      0.70 %     172
V      5.83 %    1425
a      0.20 %      50
c     18.27 %    4468
h     15.68 %    3833
l      8.82 %    2156
s      7.57 %    1851
v     15.77 %    3856
z      4.07 %     994
z;M    2.88 %     704
z;m    6.25 %    1527
SUM  100.00 %   24450
```

So `S+s` occurs `172 + 1851 = 2023` times. `C+c` occurs `571 + 4468 = 5039` times.

Note that there's no quadratics here, only cubics, probably because of whatever original program (Illustrator??) created the SVG files. If I were to convert the icons from OTF instead of from SVG, I'd possibly see quadratics but no cubics.

I don't really have a conclusion yet. Just sharing some numbers.

**Comment by Hixie** [comment]
The Flutter costs I gave covers everything from once the bytes enter the IconVG library up to and including passing the data to Skia for it to create an SkPicture, but does not include rasterization (which happens in the other 4ms budget, on the GPU controlled from a different thread of the CPU). It's size-agnostic (modulo LDO stuff in IconVG). I haven't timed the rasterisation step but it should be comparable to rasterizing the equivalent SVG file.

I should add that I've done nothing to optimize for render time, I just implemented the spec by starting at the top and doing everything it described in order. I'm sure it could be optimized further without changes to the format.

**Comment by nigeltao** [comment]
Some further ideas, not necessarily good ones, but I don't want to forget them:

- If we're simplifying, we could drop *relative* 'lower-case' drawing ops and only have *absolute* 'upper-case'  ones.
- We could re-order the arguments (so that `C` would be `(x3, y3, x2, y2, x1, y1)` instead of `(x1, y1, x2, y2, x3, y3)` so that a bunch of ops would be consistent in that the first two args are the final pen position. That might be useful if we reserve some op codes that are "ignore (if you don't understand this File Format Version), but fall back to `line_to(final_x, final_y)`". That's not entirely consistent, though, with `H/h` and `V/v` op codes.

**Comment by Hixie** [comment]
If we're removing features, removing some of the opcodes would remove the need to track certain things. For example, losing the shorthand opcodes removes the need to track what the last opcode type was (and what the last control point was). Losing H/h and V/v as well would remove the need to track the "current position" in Flutter's implementation (because our Path API has relative commands but doesn't have the equivalent of H and V which are half-relative half-absolute).

**Comment by nigeltao** [comment]
More data on decode times on a mid-range `x86_64` laptop (2016; Skylake):

```
$ cat /proc/cpuinfo | grep model.name | uniq
model name: Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz
```

With the following patch:

```
diff --git a/example/iconvg-to-png/iconvg-to-png.c b/example/iconvg-to-png/iconvg-to-png.c
index aa3d25c..38f5826 100644
--- a/example/iconvg-to-png/iconvg-to-png.c
+++ b/example/iconvg-to-png/iconvg-to-png.c
@@ -26,6 +26,7 @@
 #include <stdio.h>
 #include <stdlib.h>
 #include <string.h>
+#include <sys/time.h>
 
 // IconVG ships as a "single file C library" or "header file library" as per
 // https://github.com/nothings/stb/blob/master/docs/stb_howto.txt
@@ -385,6 +386,32 @@ main(int argc, char** argv) {
     }
   }
 
+  if (strcmp(input_filename, "askjfhkajshdfkj")) {
+    struct timeval start_tv;
+    gettimeofday(&start_tv, NULL);
+
+    const int N = 100000;
+    for (int i = 0; i < N; i++) {
+      iconvg_canvas debug_canvas = iconvg_canvas__make_debug(NULL, NULL, NULL);
+      const char* err_msg = iconvg_decode(
+          &debug_canvas, iconvg_rectangle_f32__make(0, 0, 256, 256), src_ptr,
+          src_len, NULL);
+      if (err_msg) {
+        fprintf(stderr, "main: could not decode %s\n%s\n", input_filename,
+                err_msg);
+        return 1;
+      }
+    }
+
+    struct timeval finish_tv;
+    gettimeofday(&finish_tv, NULL);
+    int64_t micros = (int64_t)(finish_tv.tv_sec - start_tv.tv_sec) * 1000000 +
+                     (int64_t)(finish_tv.tv_usec - start_tv.tv_usec);
+
+    printf("%8ld ns per decode for %s\n", (1000 * micros) / N, input_filename);
+    return 0;
+  }
+
   // Decode the IconVG.
   {
     iconvg_canvas* c = &pb.canvas;
```

I get these times (16μs tops, 0.4% of a 4000μs budget):

```
$ for f in test/data/*.ivg; do gen/bin/iconvg-to-png-with-cairo $f; done
     495 ns per decode for test/data/action-info.hires.ivg
     473 ns per decode for test/data/action-info.lores.ivg
    4522 ns per decode for test/data/arcs.ivg
     140 ns per decode for test/data/blank.ivg
    3354 ns per decode for test/data/cowbell.ivg
     591 ns per decode for test/data/elliptical.ivg
   15051 ns per decode for test/data/favicon.ivg
    1294 ns per decode for test/data/gradient.ivg
     477 ns per decode for test/data/lod-polygon.ivg
    2340 ns per decode for test/data/video-005.primitive.ivg
```

That's just decoding the ops and their arguments, including expanding 1-byte numbers to `float32` values. It doesn't include any Cairo or Skia calls.

Not sure how much of the difference is `x86_64` laptop versus `ARM` phone, how much difference is C vs Dart, how much difference is that I'm just doing a tight loop microbenchmark, etc.

**Comment by Hixie** [comment]
If I substitute the canvas class for a class that does nothing, but still run all the other logic (so I'm still building the matrices for radial gradients, tracking the current position for drawing ops, and so on), then I get these numbers for the Dart implementation running in Flutter on an i9-7900X CPU @ 3.30GHz running Linux:

```
 13,130.5ns  action-info.hires  
 10,624.9ns  action-info.lores  
 27,336.1ns  arcs               
  4,758.3ns  blank              
 59,416.7ns  cowbell            
 19,045.8ns  elliptical         
 77,464.4ns  favicon            
 30,641.8ns  gradient           
 16,159.7ns  lod-polygon        
 78,753.9ns  video-005.primitive
```

I suspect there's lots of Dart overhead here, but I haven't investigated (I'm sure I'm copying more than the C implementation would, since in idiomatic Dart you don't have pointers). It's also possible I have some dumb algorithms.

**Comment by nigeltao** [comment]
Is it easy for Dart/Flutter to wrap the C IconVG+Skia implementation (the same way it presumably wraps a PNG decoder)? Just for numbers. There's obviously memory-safety implications.

**Comment by Hixie** [comment]
(Oh actually, looking at a profile, it turns out there is a lot of Skia code being called in the measurements above since I didn't mock out the Path class.)

> Is it easy for Dart/Flutter to wrap the C IconVG+Skia implementation (the same way it presumably wraps a PNG decoder)? Just for numbers. There's obviously memory-safety implications.

One could build a custom engine that supports a new format, sure. The numbers should be more or less identical to what you'd expect outside of Flutter, there's not really any overhead added by Flutter in that kind of scenario.

**Comment by Hixie** [comment]
Did some optimising with a profiler and more or less halved the render time (I'll post a PR). Most of the time now is spent in Skia calls (manipulating the SkPath object or rendering it). That said, even with all the time spent in Skia, 10% of the time it takes to parse and render `favicon.ivg` is spent decoding coordinate numbers.

**Comment by nigeltao** [comment]
If you still want to experiment with timing / profiling 4-byte fixed width coordinates, [cowbell-4-byte-coordinates.zip](https://github.com/google/iconvg/files/6590238/cowbell-4-byte-coordinates.zip) contains two files.

`cowbell-4-byte-coordinates-still-valid.ivg` is a valid FFV 0 IconVG file. It's just that its coordinates are always encoded in 4 bytes, never 1 or 2. Being valid FFV 0 means that the low two bits are still set (and will need masking off, if you want to decode it 100% correctly, although you could probably ignore this for rough numbers, since they're the least significant bits).

`cowbell-4-byte-coordinates-invalid.ivg` goes even further and just encodes the `float32` as the equivalent IEEE 754 little-endian bits. They're no longer valid FFV 0 files because they don't set the low two bits. It's basically the first file after setting all the relevant low-two-bits to zero.

**Comment by nigeltao** [comment]
Here's a `vimdiff` screenshot showing how the `cowbell-4-byte-coordinates-still-valid.ivg` disassembly differs from `cowbell.ivg`. As you can see, the coordinates don't change, just their encoding.

![cowbell-ivg-diff](https://user-images.githubusercontent.com/8565232/120617684-b3c6ec80-c49d-11eb-9410-1c3c26eeee52.png)

**Comment by nigeltao** [comment]
[favicon-4-byte-coordinates.zip](https://github.com/google/iconvg/files/6590365/favicon-4-byte-coordinates.zip) does the same for `favicon.ivg`.

**Comment by nigeltao** [comment]
> 10% of the time it takes to parse and render favicon.ivg is spent decoding coordinate numbers.

I'm a total Dart newbie, but a few suggestions in:

```dart
double decodeCoordinateNumber() {
  final int byte1 = nextByte;
  if (byte1 & 0x01 == 0x00) {
    // 1 byte encoding (decodeRealNumber with a bias)
    return (byte1 >> 1).toDouble() - 64.0;
  }
  final int byte2 = nextByte;
  if (byte1 & 0x02 == 0x00) {
    // 2 byte encoding (decodeRealNumber with a scale and a bias)
    return ((byte1 >> 2) + (byte2 << 6)).toDouble() / 64.0 - 128.0;
  }
  // 4 byte encoding (same as decodeRealNumber)
  final int byte3 = nextByte;
  final int byte4 = nextByte;
  _buffer.setUint32(0, (byte1 & 0xFC) + (byte2 << 8) + (byte3 << 16) + (byte4 << 24));
  return _buffer.getFloat32(0);
}
```

One: insert a 'fast path' that does *one* bounds check instead of *up-to-four* (one at each of the four `nextByte` lines):

```dart
double decodeCoordinateNumber() {
  if (cursor <= bytes.length - 4) {
    uint32 /*or whatever the Dart equivalent is*/ u = bytes.loadU32LE();
    // For the remainder of this branch, work with u instead of bytes or nextByte.
    return etc;
  }
  // The rest of the function, the slow path, is the same as before.
  final int byte1 = nextByte;
  // etc
  return etc;
}
```

Two: with `return (byte1 >> 1).toDouble() - 64.0;`, does it make a difference if you move the subtraction inside the parentheses, so it's a (presumably faster) integer subtraction instead of a floating point subtraction? Ditto for the 2-byte branch.

Three: is a `ByteData` `setUint32` + `getFloat32` dance really the fastest Dart way to do what C++ calls `reinterpret_cast<float>` and in CPU terms can be a no-op??

**Comment by nigeltao** [comment]
> One could build a custom engine that supports a new format, sure. The numbers should be more or less identical to what you'd expect outside of Flutter, there's not really any overhead added by Flutter in that kind of scenario.

In case there was a mis-understanding, I was thinking more about comparing a 100% Dart decoder vs a thin Dart wrapper over the C decoder, instead of comparing Dart-with-Flutter vs Dart-without-Flutter.

**Comment by nigeltao** [comment]
I made a copy/paste error in the `*invalid.ivg` files in the two `.zip` files I uploaded earlier. Here's a new `.zip` file:
[invalid-4-byte-coordinates.zip](https://github.com/google/iconvg/files/6591241/invalid-4-byte-coordinates.zip)

And here are the timings (3 runs each):

```
    2028 ns per decode for test/data/cowbell-4-byte-coordinates-invalid.ivg
    3273 ns per decode for test/data/cowbell-4-byte-coordinates-still-valid.ivg
    3454 ns per decode for test/data/cowbell.ivg

    2032 ns per decode for test/data/cowbell-4-byte-coordinates-invalid.ivg
    3321 ns per decode for test/data/cowbell-4-byte-coordinates-still-valid.ivg
    3245 ns per decode for test/data/cowbell.ivg

    2035 ns per decode for test/data/cowbell-4-byte-coordinates-invalid.ivg
    3276 ns per decode for test/data/cowbell-4-byte-coordinates-still-valid.ivg
    3238 ns per decode for test/data/cowbell.ivg

   12770 ns per decode for test/data/favicon-4-byte-coordinates-invalid.ivg
   14936 ns per decode for test/data/favicon-4-byte-coordinates-still-valid.ivg
   14765 ns per decode for test/data/favicon.ivg

   12664 ns per decode for test/data/favicon-4-byte-coordinates-invalid.ivg
   15238 ns per decode for test/data/favicon-4-byte-coordinates-still-valid.ivg
   14760 ns per decode for test/data/favicon.ivg

   12903 ns per decode for test/data/favicon-4-byte-coordinates-invalid.ivg
   14692 ns per decode for test/data/favicon-4-byte-coordinates-still-valid.ivg
   14908 ns per decode for test/data/favicon.ivg
```

Decoding `*invalid.ivg` requires this patch:

```diff
diff --git a/release/c/iconvg-unsupported-snapshot.c b/release/c/iconvg-unsupported-snapshot.c
index 50b2f2d..83624b3 100644
--- a/release/c/iconvg-unsupported-snapshot.c
+++ b/release/c/iconvg-unsupported-snapshot.c
@@ -2065,34 +2065,13 @@ iconvg_private_decoder__skip_to_the_end(iconvg_private_decoder* self) {
 static bool  //
 iconvg_private_decoder__decode_coordinate_number(iconvg_private_decoder* self,
                                                  float* dst) {
-  if (self->len >= 1) {
-    uint8_t v = self->ptr[0];
-    if ((v & 0x01) == 0) {  // 1-byte encoding.
-      int32_t i = (int32_t)(v >> 1);
-      *dst = ((float)(i - 64));
-      self->ptr += 1;
-      self->len -= 1;
-      return true;
-
-    } else if ((v & 0x02) == 0) {  // 2-byte encoding.
-      if (self->len >= 2) {
-        int32_t i = (int32_t)(iconvg_private_peek_u16le(self->ptr) >> 2);
-        *dst = ((float)(i - (128 * 64))) / 64.0f;
-        self->ptr += 2;
-        self->len -= 2;
-        return true;
-      }
-
-    } else {  // 4-byte encoding.
-      if (self->len >= 4) {
-        // TODO: reject NaNs?
-        *dst = iconvg_private_reinterpret_from_u32_to_f32(
-            0xFFFFFFFCu & iconvg_private_peek_u32le(self->ptr));
-        self->ptr += 4;
-        self->len -= 4;
-        return true;
-      }
-    }
+  if (self->len >= 4) {
+    // TODO: reject NaNs?
+    *dst = iconvg_private_reinterpret_from_u32_to_f32(
+        iconvg_private_peek_u32le(self->ptr));
+    self->ptr += 4;
+    self->len -= 4;
+    return true;
   }
   return false;
 }
```

**Comment by Hixie** [comment]
> One: insert a 'fast path' that does _one_ bounds check instead of _up-to-four_ (one at each of the four `nextByte` lines):

Yeah, there's a bunch of changes like that that could be made (basically anywhere that currently calls nextByte should be optimized to work in bigger chunks -- ideally we'd actually inline all the nextByte work). The trade-off is implementation complexity and an increased maintenance burden since now the code no longer exactly matches the spec word for word. Since the spec is still in flux I'd rather wait before making that kind of optimization.

> Two: with `return (byte1 >> 1).toDouble() - 64.0;`, does it make a difference if you move the subtraction inside the parentheses, so it's a (presumably faster) integer subtraction instead of a floating point subtraction? Ditto for the 2-byte branch.

That might make a difference, yeah.


> Three: is a `ByteData` `setUint32` + `getFloat32` dance really the fastest Dart way to do what C++ calls `reinterpret_cast<float>` and in CPU terms can be a no-op??

Sadly yes. q.v. https://github.com/dart-lang/sdk/issues/46195


> In case there was a mis-understanding, I was thinking more about comparing a 100% Dart decoder vs a thin Dart wrapper over the C decoder, instead of comparing Dart-with-Flutter vs Dart-without-Flutter.

Ah, got it. I'm sure a pure C decoder would be faster, if for no other reason that you'd avoid the need for the Dart<->C bridge (which, while fast, is not a no-op), GC (which, while fast, is not a no-op), and would be able to do direct pointer math, unsafe casting, and other such things which are super useful when parsing a binary format and not available to Dart currently.

Currently we don't have a way to do plugins for that kind of thing though. We've talked about offering an API like that it in the past but I don't think it's gotten past the [design stage](https://docs.google.com/document/d/1xG7jR4FserdW7TdwnklF3_lXUGmt4myPQjDGF3LFtCQ/edit?resourcekey=0-Iug4D2mWuyQI6suvC_2itw). (It's tricky because it essentially means exposing all of Skia and Dart's internal C APIs as part of the API surface we support, which is a big responsibility to take on.)

**Comment by nigeltao** [comment]
This issue (#18) now conflates several ideas:
1. The spec could be clarified.
2. Dropping some opcodes would simplify things. This could be a combination of `A/a` arc ops, `S/s/T/t` smooth ops, 'lower case' relative ops and `H/V` half-relative-half-absolute ops.
3. Timing data for decoding short (encoded as 1, 2 byte) and long (4 byte) coordinates.
4. Optimizing the Dart implementation.

An issue was coincidentally just filed which discusses idea (2), dropping opcodes, so let's move discussion of that idea to #29.

Of what remains, let's try to focus this issue back on (1), and file other issues if we want to discuss (3) or (4).
