### ISSUE TITLE
Can LOD be set to NaN?

### ISSUE THREAD

**Issue by lifthrasiir** [google/iconvg#32]
The specification states that:

> It is valid for the 4 byte encoding to represent infinities and `NaN`s, but if not loaded into `LOD0` or `LOD1`, the subsequent rendering is undefined.

This suggests that LOD0/1 can be set to NaN, but nowhere in the spec mentions the behavior in that case.

**Comment by nigeltao** [comment]
The spec says:

> Drawing mode opcodes have no effect (other than leaving drawing mode) unless the height `H` in pixels of the rasterization satisfies `(LOD0 <= H)` and `(H < LOD1)`.

If e.g. `LOD0` is `NaN` then `(LOD0 <= H)` is always false, so drawing mode opcodes have no effect.

**Comment by lifthrasiir** [comment]
It makes sense, but it would be nice to explicitly mention that:

* `LOD0 > LOD1` is possible since other places like gradient stops make misordered numbers invalid; and
* Both can be NaN since it is the only place where NaN is allowed.
