### ISSUE TITLE
Clarity on LOD Jump decoding

### ISSUE THREAD

**Issue by 1ntEgr8** [google/iconvg#39]
The spec mentions that an LOD Jump is followed by two **floating point numbers**
> The JumpCount is followed by two floating point numbers, LOD0 and LOD1

However, in tests/data/lod-polygon.iconvg.disassembly, they appear to be decoded as coordinate numbers.
```
3a            #0003 Jump Level-of-Detail
07                  Target: #0007 (PC+3)
81                  +0
02 d0               +80
```

The spec mentions early on that floating point numbers always take four bytes.
> Floating point numbers are always encoded in 4 bytes: the little-endian encoding of a 32-bit IEEE 754 float32 number.

Following this leads to incorrectly decoding lod-polygon.

I suggest the verbage be updated to say that LOD0 and LOD1 are coordinate numbers.

## Specifications

- Version: FVV1
- Platform: N/A

**Comment by nigeltao** [comment]
Thanks for the bug reports!
